name: Check Style Code

on:
  push:
    branches:
      - pomosh

  pull_request:
    branches:
      - master
      - pomosh
jobs:
  checkcode_project:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set version Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run linter
        run: |
          flake 8 .